### ISSUE TITLE
[11.0] deleted jobs run again and again

### ISSUE THREAD

**Issue by Gokulakannanaj** [OCA/queue#106]
If process is failed, i don't want to re-queue it.so i'm trying to delete the failed jobs.it's also deleted. But after some time failed process automatically created and jobs also failed.

Expected Behavior:
Failed process don't run after it deleted.

**Comment by lmignon** [comment]
@Gokulakannanaj Thank you for the report. Nevertheless, I've some difficulties to understand what's the problem. If a process creates jobs that fail at execution it's not the responsibility of the queue framework to prevent the creation of the same kind of jobs. The causes of a job process error can be multiple. In some cases, they may be temporary, in other cases related to an external context at the time of execution. IMO there is no rule to say that such a job should no longer be performed if the previous one has failed.

**Comment by guewen** [comment]
Did you fixed your deployment since #103? If not it might cause unexpected problems.
In any case, I don't understand your description.

**Comment by Gokulakannanaj** [comment]
Process state changed to failed due to some issue(Like validation error). Now i delete the failed records(consider record 1) from database.Fine.But after some time, deleted record(record 1) created automatically.

**Comment by guewen** [comment]
This is the expected behavior, if you have a trigger for a job, it will create a new job no matter what you had before, on purpose. 

You may want to check again what is delaying your job in your code and the job function itself: you should never have a failed job, you should handle the failure in a proper way in your job's code. 

Example: if you want to never delay a job again for a record when have a kind of validation error, then in your job instead of letting the exception bubble up to the job, the code of the job should catch the error, add a flag on the record that marks it as "don't delay the job again" and let the job finish properly (done, not failed).

**Comment by Gokulakannanaj** [comment]
But now i remove the failed record then why its created automatically ?
I have no trigger and also max retries is 1.I deleted the record then why its come again ?

**Comment by guewen** [comment]
There is no way to delete a job from the UI, because it's not what you should do. You have to set a job as "done" if you want to ignore the failure.

**Comment by Gokulakannanaj** [comment]
Hi @guewen is it possible to avoid recreation without set done?
For example changing retries as 1 or something else

**Comment by guewen** [comment]
I can't help you because I can't understand what your exact problem is. You may want to learn from http://www.catb.org/esr/faqs/smart-questions.html about better ways to be helped.
