### ISSUE TITLE
[Feature] Add a cancel state on queue.job

### ISSUE THREAD

**Issue by benwillig** [OCA/queue#143]
Actually, when you don't want to process a job, you would use the "Set to done" button. The problem is that you can't easily see which job have been processed, and which job have been manually done by a user.

So the idea is to add a "Cancel" state. A wizard would also be available in the tree view to cancel more than one job at a time.

I would like your opinion @guewen before starting to develop it.

**Comment by guewen** [comment]
This was an option that we decided to exclude at the beginning because it doesn't bring so much and add complexity. I still have this opinion.
The result of a job set to done contains "Manually set to done by ..." which allows to find such jobs. Also, I think that manually setting jobs to done should be an exception, in an ideal world, it should never happen. If you need to do it regularly, I'm curious to know the use case.

What we could consider however, is to ask for a reason in the "set to done" wizard, which would be stored in the result: seems even better as you keep a trace of why you needed to do that.

**Comment by benwillig** [comment]
Thanks for your feedback. I totally understand. So if we create a wizard which will be called in the 'Set to done' button to ask a reason, it would be ok for you? This wizard would also be available in the tree view.

**Comment by guewen** [comment]
> hanks for your feedback. I totally understand. So if we create a wizard which will be called in the 'Set to done' button to ask a reason, it would be ok for you? This wizard would also be available in the tree view

Yes, the wizard already exists, but the "reason" is hardcoded as "Manually set to done by ..." for now.
I think the only change is to add a field on the wizard and set it as the job's result.

**Comment by guewen** [comment]
Done in #149
