### ISSUE TITLE
Running one job at same time [13]

### ISSUE THREAD

**Issue by ghost** [OCA/queue#204]
Hi i am configured queue root sub channel with 4 worker. 
and i can see log this:

odoo.addons.queue_job.jobrunner.channels: Configured channel: root.sender(C:4,Q:0,R:0,F:0)

but only one job starting at one time not 4 ? what i am missing ?

**Comment by guewen** [comment]
Hi,

Do you have some jobs stuck in `started` or `enqueued`?
Did you set a special configuration in `ODOO_QUEUE_JOB_CHANNELS`?
How many odoo workers (`--workers`) did you start?

**Comment by ghost** [comment]
no there any stuck job,
in odoo.conf workers = 8
and my service Environment=ODOO_QUEUE_JOB_CHANNELS=root.sender:4

**Comment by guewen** [comment]
I'm actually not sure what happens (and what should happen) when you configure `ODOO_QUEUE_JOB_CHANNELS=root.sender:4` since you do not configure the root channel. You have to configure the `root` channel: `ODOO_QUEUE_JOB_CHANNELS=root:4` or `ODOO_QUEUE_JOB_CHANNELS=root:4,root.sender:4`.
My guess is that the `root` channel is started with a capacity of 1 which is the default value, so even if jobs are pushed in the `root.sender` channel with 4 slots, they are then restrained by the `root` channel having 1 slot.

**Comment by ghost** [comment]
thank you quewen after configure root:4 its begin worked !
