### ISSUE TITLE
RetryableJobError does not Rollback Transaction

### ISSUE THREAD

**Issue by wpichler** [OCA/queue#261]
Hi all,

i have an issue with the RetryableJobError - when i raise this error in the middle of a job (eg. some data already got changed), then it will not issue a Rollback - because it does not raise the error forward to the main odoo code - so the transaction will get commited.

Is this really a wanted behaviour ?

It would be great if we could add here an option to the RetryableJobError to rollback the transaction..

Code in question is here:
https://github.com/OCA/queue/blob/a5afdb344b21c9669f8625afe19920daa4590495/queue_job/controllers/main.py#L108

**Comment by guewen** [comment]
Hi @wpichler, this is not wanted, it must rollback.

**Comment by wpichler** [comment]
Ok, should i create a PR for this - or do you want to fix this ?

**Comment by guewen** [comment]
I don't think I would be able until a couple of weeks, so if you can take it, I'm pleased :)

**Comment by theangryangel** [comment]
Sorry for injecting myself into the conversation...

FWIW I've been wrapping critical sections of jobs with savepoints to safe guard against this (i.e. after I've finished processing from third party systems, but before I've started modifying records in Odoo). I had just assumed it was intentional for a use case... I'm just wondering if there is there a compelling reason to keep it as-is and turn this into a documentation issue?

**Comment by agent-z28** [comment]
@guewen any news on this, shouldn't the fix do the job?

**Comment by agent-z28** [comment]
@wpichler wolfgang is the code propper working?

**Comment by wpichler** [comment]
Its working for me on a production system now for around 2 months

**Comment by agent-z28** [comment]
@wpichler great, i will try it! nice job
