### ISSUE TITLE
Issue: jobs relaunching in infinite loop 

### ISSUE THREAD

**Issue by ecino** [OCA/queue#34]
We have a strange issue:
when running the queue_job with workers we have some jobs that are re-processing in infinite times making 100% resource usage on our server, and then Odoo becomes unusable. We can see the following logs in the console:
```
017-10-06 17:48:07,472 25098 WARNING compassion odoo.addons.queue_job.controllers.main: job 9e56cf5e-f3ea-4ea1-937f-c3973ed766b6 is in state done instead of enqueued in /runjob
```
Our config file looks like this:
```
;increase ram for letter import
limit_memory_soft = 629145600
limit_memory_hard = 1677721600

; don't limit time for workers
limit_time_cpu = 90000
limit_time_real = 96000

workers = 8
server_wide_modules = web,web_kanban,queue_job,mail_tracking,mail_sendgrid

[queue_job]
channels = root:7,root.recurring_invoicer:1,root.sbc_compassion:1
port = 8069
```

Any thoughts what could happen? When disabling the workers we don't have the issue anymore, but the jobs are not executed.

**Comment by guewen** [comment]
I observes this behavior when the soft memory limit is reached by the
workers as soon as they answer to their first request, so they restart in a
loop. Could you check in the logs with debug level if you see anything
regarding restarting workers / memory reached?

Le 6 oct. 2017 19:55, "ecino" <notifications@github.com> a écrit :

We have a strange issue:
when running the queue_job with workers we have some jobs that are
re-processing in infinite times making 100% resource usage on our server,
and then Odoo becomes unusable. We can see the following logs in the
console:

017-10-06 17:48:07,472 25098 WARNING compassion
odoo.addons.queue_job.controllers.main: job
9e56cf5e-f3ea-4ea1-937f-c3973ed766b6 is in state done instead of
enqueued in /runjob

Our config file looks like this:

;increase ram for letter import
limit_memory_soft = 629145600
limit_memory_hard = 1677721600

; don't limit time for workers
limit_time_cpu = 90000
limit_time_real = 96000

workers = 8
server_wide_modules = web,web_kanban,queue_job,mail_tracking,mail_sendgrid

[queue_job]
channels = root:7,root.recurring_invoicer:1,root.sbc_compassion:1
port = 8069

Any thoughts what could happen? When disabling the workers we don't have
the issue anymore, but the jobs are not executed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OCA/queue/issues/34>, or mute the thread

**Comment by ecino** [comment]
Thanks @guewen , we increased the soft memory limit and now it's working! I close the issue.

**Comment by simahawk** [comment]
@ecino would you mind contributing by updating "known issues" section here? https://github.com/OCA/queue/tree/10.0/queue_job#known-issues--roadmap
