### ISSUE TITLE
[13.0] [14.0] company_id should be preserved when a delayed method is executed

### ISSUE THREAD

**Issue by lmignon** [OCA/queue#363]
When a job is cretated, the current company [is stored into the job info](https://github.com/OCA/queue/blob/13.0/queue_job/job.py#L493).  Nevertheless, when a job is performed, it seems that the company is not restored into the running context...
Do I miss something or should we modify the [`func`](https://github.com/OCA/queue/blob/13.0/queue_job/job.py#L630) method to call the with_company method on the recordset before the call o the dlayed method? 
```python
    def func(self):
        recordset = self.recordset.with_context(job_uuid=self.uuid).with_company(self.company_id)
        return getattr(recordset, self.method_name)
```

**Comment by lmignon** [comment]
ping @simahawk @guewen @Cedric-Pigeon

**Comment by guewen** [comment]
I think the initial goal to have the company was to have a security rule based on it (https://github.com/OCA/connector/commit/bff6ca3983d660931cd79362d6950e1472e3d0d0). I'd prefer not to have this security rule by default BTW, this is the first thing I used to disable on any project (or forget to do it then shoot myself in the foot because I don't see all the jobs :D), but I digress.

Indeed, we should keep the company. It seems to be a great opportunity to store the context in the `JobSerialized` records field (https://github.com/OCA/queue/issues/283). We could start with a simple allow-list of key to keep, including the various company context keys.

**Comment by Cedric-Pigeon** [comment]
I agree with @guewen. Limiting the view of jobs per companies is a nightmare and it is also the first thing I disable.
About the company used for the job itself I think it must be related to the user running the job.

**Comment by lmignon** [comment]
The company used to run the job must be the one the active one at the time the job has been scheduled. Otherwise, we've weird issues with multi company users if they change the active company before a scheduled job is performed.

**Comment by Cedric-Pigeon** [comment]
@lmignon yes you are right

**Comment by pedrobaeza** [comment]
Since v13, the company is not managed through context, so IMO the job should recreate the environment with the main company and the rest of them displayed the same as when you perform the enqueuing.

**Comment by lmignon** [comment]
@pedrobaeza The fields `company` and  `companies` on the env are both initialized from the `allowed_company_ids` values (https://github.com/odoo/odoo/blob/14.0/odoo/api.py#L555) . Therefore, if we store and restore the context,  we don't need to explicitly call  `with_company` and we are sure that the job will be executed on the right company. Therefore the @guewen 's proposal seems to be the right way to go..

**Comment by pedrobaeza** [comment]
Great then. I didn't know they kept the same for v14, as there was a change from v13 to v14 from `with_context(force_company=X)` to `with_company(x)`.
