### ISSUE TITLE
One anonymous session opened per job run

### ISSUE THREAD

**Issue by guewen** [OCA/queue#44]
The job runner sends HTTP GET to push the jobs, which on the Odoo side, create one anonymous session file for each request. I discuss this problem on the code for the version 9.0 because this is where I was working on. See https://github.com/OCA/connector/pull/270

**Comment by whulshof** [comment]
Would the pull request also work on 10.0 or do I have to modify it? Probably dumb question, but I don't have the time right now to look into it and I do have trouble with huge amount of sessions. I could do some of the thorough testing as mentioned by @guewen though.

**Comment by guewen** [comment]
@whulshof I ported the pull request here: https://github.com/OCA/queue/pull/53
I'd love your feedback :)

**Comment by sbidoul** [comment]
@guewen do you have good results with this in production? We'll probably deploy it too.

**Comment by whulshof** [comment]
@guewen thanks a lot. Will deploy right away and tell you!


Met vriendelijke groet/Kind regards,

Magnus Red

Willem Hulshof

+31 88 696 60 00 | +31 651 243 710 | www.magnus.nl<http://www.magnus.nl/red/>

[id:4FD331F6-E3AE-4679-826C-9D6015959C97]
Van: Guewen Baconnier <notifications@github.com>
Beantwoorden - Aan: OCA/queue <reply@reply.github.com>
Datum: donderdag 8 februari 2018 om 12:17
Aan: OCA/queue <queue@noreply.github.com>
CC: Willem Hulshof <w.hulshof@magnus.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [OCA/queue] One anonymous session opened per job run (#44)


@whulshof<https://github.com/whulshof> I ported the pull request here: #53<https://github.com/OCA/queue/pull/53>
I'd love your feedback :)

**Comment by guewen** [comment]
> do you have good results with this in production? We'll probably deploy it too.

@sbidoul Yes! So far so good. It helps a lot to keep a low number of sessions and we didn't had any side effects (at least observed) :)

@whulshof could you give it a try?

**Comment by whulshof** [comment]
It is a pity, that I just installed it in Test and we went live so test is not used that much. But I’m thinking about production, because I have 3000 sessions now, which is rather high for a maybe 100 named users system. On the other hand, it shouldn’t be noticeable in the system. I’ll try it tonight.


Met vriendelijke groet/Kind regards,

Magnus Red

Willem Hulshof

+31 88 696 60 00 | +31 651 243 710 | www.magnus.nl<http://www.magnus.nl/red/>

[id:4FD331F6-E3AE-4679-826C-9D6015959C97]
Van: Guewen Baconnier <notifications@github.com>
Beantwoorden - Aan: OCA/queue <reply@reply.github.com>
Datum: dinsdag 6 maart 2018 om 11:34
Aan: OCA/queue <queue@noreply.github.com>
CC: Willem Hulshof <w.hulshof@magnus.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [OCA/queue] One anonymous session opened per job run (#44)


do you have good results with this in production? We'll probably deploy it too.

@sbidoul<https://github.com/sbidoul> Yes! So far so good. It helps a lot to keep a low number of sessions and we didn't had any side effects (at least observed) :)

@whulshof<https://github.com/whulshof> could you give it a try?

**Comment by sbidoul** [comment]
@Cedric-Pigeon if not done yet, can you deploy this in production and report your findings?

**Comment by whulshof** [comment]
@sbidoul and @guewen After running for a day with 240 queue.jobs sessions remain at 50-60, which is to be expected. No side-effects until now.

Question: would it be possible that large number of sessions lead to more used connections to postgres and therefor possible overshoot in max-connections?


Met vriendelijke groet/Kind regards,

Magnus Red

Willem Hulshof

+31 88 696 60 00 | +31 651 243 710 | www.magnus.nl<http://www.magnus.nl/red/>

[id:4FD331F6-E3AE-4679-826C-9D6015959C97]
Van: Guewen Baconnier <notifications@github.com>
Beantwoorden - Aan: OCA/queue <reply@reply.github.com>
Datum: dinsdag 6 maart 2018 om 11:34
Aan: OCA/queue <queue@noreply.github.com>
CC: Willem Hulshof <w.hulshof@magnus.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [OCA/queue] One anonymous session opened per job run (#44)


do you have good results with this in production? We'll probably deploy it too.

@sbidoul<https://github.com/sbidoul> Yes! So far so good. It helps a lot to keep a low number of sessions and we didn't had any side effects (at least observed) :)

@whulshof<https://github.com/whulshof> could you give it a try?

**Comment by guewen** [comment]
> Question: would it be possible that large number of sessions lead to more used connections to postgres and therefor possible overshoot in max-connections?

I don't think. I don't see any way web sessions and postgres connections would be related.

**Comment by guewen** [comment]
Thank you for your feedback @whulshof!

**Comment by whulshof** [comment]
I still have quite high numbers of sessions generated. After not monitoring for a month the number was some 8000 (!). After deletion and in a few days with a lot of Job Queue activity, the number again increased from 0 to 2000 sessions whereas there are some 50-100 human users. I get the feeling we didn't really solve this problem yet. @guewen @sbidoul any second thoughts about it?

**Comment by guewen** [comment]
@whulshof Are you sure they are not generated by something else, such as a healthcheck or uptime check?

On a production system with the patch applied since a couple of months, the session count stays slow.
2039 sessions at the moment, with 1'132'203 jobs the last 30 days

![selection_287](https://user-images.githubusercontent.com/417223/40055712-2addcf6a-5849-11e8-9e2d-826dded756d3.png)
![selection_288](https://user-images.githubusercontent.com/417223/40055713-2af613d6-5849-11e8-832a-bda687556b06.png)

**Comment by whulshof** [comment]
@guewen I’m not sure, but in max one week and only a fraction of your number of jobs the number of anonymous sessions is 1400.


Met vriendelijke groet/Kind regards,

Magnus Red

Willem Hulshof

+31 88 696 60 00 | +31 651 243 710 | www.magnus.nl<http://www.magnus.nl/red/>

[id:4FD331F6-E3AE-4679-826C-9D6015959C97]
Van: Guewen Baconnier <notifications@github.com>
Beantwoorden - Aan: OCA/queue <reply@reply.github.com>
Datum: dinsdag 15 mei 2018 om 14:07
Aan: OCA/queue <queue@noreply.github.com>
CC: Willem Hulshof <w.hulshof@magnus.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [OCA/queue] One anonymous session opened per job run (#44)


@whulshof<https://github.com/whulshof> Are you sure they are not generated by something else, such as a healthcheck or uptime check?

On a production system with the patch applied since a couple of months, the session count stays slow.
2039 sessions at the moment, with 1'132'203 jobs the last 30 days

[selection_287]<https://user-images.githubusercontent.com/417223/40055712-2addcf6a-5849-11e8-9e2d-826dded756d3.png>
[selection_288]<https://user-images.githubusercontent.com/417223/40055713-2af613d6-5849-11e8-832a-bda687556b06.png>
