### ISSUE TITLE
Queue Job Runner tries sometimes to access the same queue_job several times

### ISSUE THREAD

**Issue by christophlsa** [OCA/queue#81]
Does someone ever faced the issue that the queue job runners are logging almost every seconds that they want to access the same queue job again?

Here are the logs:

```
2018-06-13 12:30:44,361 5 INFO ? odoo.addons.queue_job.jobrunner.runner: asking Odoo to run job 7cb9e355-bafc-4ede-b17a-3f8ce1dceba1 on db odoodb
2018-06-13 12:30:44,422 5 INFO ? requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost
2018-06-13 12:30:45,477 5 INFO ? odoo.addons.queue_job.jobrunner.runner: asking Odoo to run job 7cb9e355-bafc-4ede-b17a-3f8ce1dceba1 on db odoodb
2018-06-13 12:30:45,486 5 INFO ? requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost
2018-06-13 12:30:46,653 5 INFO ? odoo.addons.queue_job.jobrunner.runner: asking Odoo to run job 7cb9e355-bafc-4ede-b17a-3f8ce1dceba1 on db odoodb
2018-06-13 12:30:46,689 5 INFO ? requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost
2018-06-13 12:30:47,855 5 INFO ? odoo.addons.queue_job.jobrunner.runner: asking Odoo to run job 7cb9e355-bafc-4ede-b17a-3f8ce1dceba1 on db odoodb
2018-06-13 12:30:48,156 5 INFO ? requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost
2018-06-13 12:30:50,465 5 INFO ? odoo.addons.queue_job.jobrunner.runner: asking Odoo to run job 7cb9e355-bafc-4ede-b17a-3f8ce1dceba1 on db odoodb
2018-06-13 12:30:50,487 5 INFO ? requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost
```

There are more log lines but they are the some. I also had the issue one time that the jobrunner tried to access two different queue jobs several times.

For me only restarting odoo helped. Right now we don't have a separate odoo instance for the queue jobs (it's planned, I saw the comments in other issues). This problem results in the issue that no other requests are possible anymore which makes this annoying.

This problem happens really rarely. Maybe one time per month (or less) but last time it happened twice in the same week. Next time I try to use `kill -3` to see why the normal workers also not responding any more.

Until I have better logs: Do you every faced the issue or have any idea why this could happen?

**Comment by sbidoul** [comment]
I notice a one second delay between tries. This is normal behaviour of the job runner when no worker is available to process the request. So this is most probably an issue else where than the job runner. You'll need to investigate why all your workers are stuck. kill -3 is a good idea indeed.

Make sure you have enough workers compared to the capacity of the root channel. You need at the very minimum 3 workers more than the capacity of the root channel.

**Comment by guewen** [comment]
> Make sure you have enough workers compared to the capacity of the root channel. You need at the very minimum 3 workers more than the capacity of the root channel.

Check also that you don't have jobs which are exhausting the memory of the workers and making them restart over and over.

**Comment by faiyeah** [comment]
Hi, 

I found this job_queue suites of plugins very useful, this is so far the most match to the functionalities I desire. 

I am using the entire job_queue suites with odoo 10. And this is my architecture and settings. 

My platform:
- CentOS 7.4
- Odoo 10
- PSQL 9.6.3

I have two odoo nodes. 

Odoo - Master node (A):

odoo.conf:
`workers = 5
xmlrpc_port = 8069
limit_memory_soft = 671088640
limit_time_real = 300
limit_time_cpu = 300
proxy_mode = True
server_wide_modules = web,queue_job
[queue_job]
channels = root:2`

Odoo - Queue runner node (B):
odoo.conf:
`workers = 2
xmlrpc_port = 8096
limit_memory_soft = 671088640
limit_time_real = 0
limit_time_cpu = 300
proxy_mode = True
server_wide_modules = web,queue_job`

The idea behind for this setup is that:
- A is the original odoo node, which serves original requests, with worker timeout of 5 min. 
- B is the job runner odoo node, which will serve job from job queue by the 2 workers, with no worker timeout. 
- So that jobs in B won't block A to serve requests. 

I have a schedule job in "A" which will be scheduled running every min, and I have put it to execute by job_queue (thanks job_queue_cron plugin). 

Per my testing, the result is:
- It happens very often that when a job is queued by A, both workers from B will process the job. 
`Jul  3 16:14:40 - warning clouderp openerp.addons.queue_job.controllers.main: pid = 26407, job_uuid = 1afcd932-5498-4dc3-a5da-a85ce7b237ec
Jul  3 16:14:40 - warning clouderp openerp.addons.queue_job.controllers.main: pid = 26406, job_uuid = 1afcd932-5498-4dc3-a5da-a85ce7b237ec
Jul  3 16:14:40 - warning clouderp openerp.addons.queue_job.controllers.main: Run job now: pid = 26407, job_uuid = 1afcd932-5498-4dc3-a5da-a85ce7b237ec
Jul  3 16:14:40 - warning clouderp openerp.addons.queue_job.controllers.main: Run job now: pid = 26406, job_uuid = 1afcd932-5498-4dc3-a5da-a85ce7b237ec`

- This will yield the errors:
`Jul  3 16:14:40 - err clouderp openerp.sql_db: bad query: UPDATE "queue_job" SET "retry"=0,"user_id"=1,"date_done"=NULL,"state"='started',"company_id"=1,"priority"=5,"max_retries"=5,"eta"=NULL,"result"=NULL,"date_enqueued"='2018-07-03 08:14:39',"exc_info"=NULL,"date_started"='2018-07-03 08:14:40' WHERE id IN (1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update
Jul  3 16:14:40 - err clouderp openerp.sql_db: bad query: UPDATE "queue_job" SET "retry"=1,"user_id"=1,"date_done"='2018-07-03 08:14:40',"state"='done',"company_id"=1,"priority"=5,"max_retries"=5,"eta"=NULL,"result"=NULL,"date_enqueued"='2018-07-03 08:14:39',"exc_info"=NULL,"date_started"='2018-07-03 08:14:40' WHERE id IN (1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update`

I have rerun the test with following two configs:
- Config 1 - Remove node B, node A also runs the job runner (of coz the job runner worker in node A will have 5 min timeout). In this case, node A queues the jobs and dequeues the jobs.
- Config 2 - Keep node A and node B, reduce the number of worker in node B to 1.

Both configs works like a charm without any issue. 

I wonder if my architecture and settings makes sense or the current implementation just simply cannot have more than one runner. 

Thanks for answering.

**Comment by christophlsa** [comment]
I close this issue.

After we started a separate odoo for the jobrunner we didn't experienced this issue again (I guess).
